spring:
  profiles:
    active: eureka1
---
spring:
  profiles: eureka1
server:
  port: 7001
eureka:
  instance:
    hostname: eureka1.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/, http://eureka3.com:7003/eureka/

---
spring:
  profiles: eureka2
server:
  port: 7002
eureka:
  instance:
    hostname: eureka2.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/, http://eureka3.com:7003/eureka/

---
spring:
  profiles: eureka3
server:
  port: 7003
eureka:
  instance:
    hostname: eureka3.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/, http://eureka2.com:7002/eureka/

