server:
  port: 7800

spring:
  application:
    name:  infrastructure-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Lingzhi-Ouyang/microservice-demo.git
          search-paths:
            - config-repo
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka