name: Config-Broadcast

on:
  push:
    branches:
      - master

jobs:
  Config-Broadcast:
    name: broadcast
    runs-on: ubuntu-latest

    steps:
    - name: configuration broadcast to gateway 
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
