name: Config-Broadcast

on:
  push:
    branches:
      - master

jobs:
  Config-Broadcast:
    name: broadcast
    runs-on: ubuntu-latest

    steps:
    - name: configuration broadcast to gateway 
      run: |
        curl -X GET http://localhost:8011/send
